"use client";

import React from "react";
import styles from "./page.module.css";
import useSWR from "swr";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Image from "next/image";

export const metadata = {
  title: "DigitalWisperer Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  const session = useSession();
  const router = useRouter();

  const fetcher = (...args) => fetch(...args).then((res) => res.json());

  const { data, mutate, error, isLoading } = useSWR(
    `http://localhost:3000/api/v1/posts?username=${session?.data?.user.name}`,
    fetcher
  );

  if (session.status === "loading" || isLoading) {
    return <p>Loading......</p>;
  }

  if (session.status === "unauthenticated") {
    return router?.push("/dashboard/login");
  }

  const handleSubmit = async (e) => {
    e.preventDefault();

    const title = e.target[0].value;
    const desc = e.target[1].value;
    const img = e.target[2].value;
    const content = e.target[3].value;

    try {
      await fetch("/api/v1/posts", {
        method: "POST",
        body: JSON.stringify({
          title,
          desc,
          img,
          content,
          username: session.data.user.name,
        }),
      });
      mutate();
      e.target.reset();
    } catch (err) {
      throw new Error(err);
    }
  };

  const deleteHandler = async (id) => {
    try {
      await fetch(`/api/v1/posts/${id}`, { method: "DELETE" });
      mutate();
    } catch (err) {
      throw new Error(err);
    }
  };

  if (session.status === "authenticated") {
    return (
      <div className={styles.container}>
        <div className={styles.posts}>
          {isLoading
            ? "Loading....."
            : data.map((post) => (
                <div className={styles.post} key={post._id}>
                  <div className={styles.imgContainer}>
                    <Image src={post.img} alt="image" width={160} height={90} />
                  </div>
                  <h2 className={styles.title}>{post.title}</h2>
                  <span
                    className={styles.deletebtn}
                    onClick={() => deleteHandler(post._id)}
                  >
                    X
                  </span>
                </div>
              ))}
        </div>
        <div className={styles.new}>
          <form className={styles.new} onSubmit={handleSubmit}>
            <h1>Add New Post</h1>
            <input type="text" placeholder="Title" className={styles.input} />
            <input
              type="text"
              placeholder="Descreption"
              className={styles.input}
            />
            <input
              type="text"
              placeholder="Image URL"
              className={styles.input}
            />
            <textarea
              className={styles.textArea}
              placeholder="Content"
              cols="30"
              rows="10"
            ></textarea>
            <button className={styles.btn} type="submit">
              Upload
            </button>
          </form>
        </div>
      </div>
    );
  }
};

export default Dashboard;
