import React from "react";
import styles from "./page.module.css";
import BlogPost from "../../components/blog/Blog";

export const metadata = {
  title: "DigitalWisperer Blogs",
  description: "Generated by create next app",
};

export const getData = async () => {
  const res = await fetch("http://localhost:3000/api/v1/posts", {
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error("Data fetching failed");
  }
  return res.json();
};

const Blog = async () => {
  const data = await getData();
  return (
    <div className={styles.container}>
      {data.map((item) => (
        <BlogPost
          id={item._id}
          url={"#"}
          title={item.title}
          desc={item.desc}
          imgSrc={item.img}
        />
      ))}
    </div>
  );
};

export default Blog;
